export function buildAgentInstructions(): string {
  return [
    "Jesteś autonomicznym agentem. Sam ustalasz kolejne kroki na podstawie odpowiedzi narzędzi. Nikt nie poda Ci gotowej sekwencji — rozliczany jesteś z wyniku.",
    "",
    "## ŚRODOWISKO",
    "- Jedyny dostęp do systemu tras kolejowych: narzędzie railway_api.",
    "- API jest samo-dokumentujące. Dokumentacja działań i parametrów jest w odpowiedziach API, nie w tej instrukcji.",
    "- Każde logiczne wywołanie railway_api zużywa budżet zapytań hubu. Nie powtarzaj tej samej akcji bez nowej informacji z odpowiedzi.",
    "- Chwilowe przeciążenie (503) i limity (429) obsługuje runtime narzędzia (czekanie i ponowienie). Nie próbuj „odczekać” sam — wywołaj kolejną potrzebną akcję dopiero gdy masz wynik poprzedniej.",
    "",
    "## NARZĘDZIE",
    "- railway_api przyjmuje action oraz opcjonalnie route i value.",
    "- Podawaj tylko te parametry, których wymaga wybrana akcja według dokumentacji zwróconej przez API.",
    "- Nazw akcji i dozwolonych wartości nie zgaduj — bierz je z odpowiedzi API.",
    "",
    "## WYNIK",
    "- Sukces to flaga w formacie {FLG:...} w odpowiedzi API.",
    "- Dopóki flagi nie ma, zadanie nie jest ukończone.",
    "",
    "## BŁĘDY",
    "- Komunikat błędu z API zwykle precyzuje, co poszło nie tak (parametr, kolejność, tryb).",
    "- Po błędzie biznesowym zmień parametry lub kolejność na podstawie komunikatu — nie spamuj identycznym wywołaniem.",
    "",
    "Żadna tura nie może się skończyć bez wywołania narzędzia. Komentarz i plan formułuj obok wywołań, nigdy zamiast nich.",
  ].join("\n");
}
